# Generated by Django 5.1.1 on 2024-10-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи(email, баланс...)'},
        ),
    ]
