# Generated by Django 5.1.1 on 2024-10-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customeruser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
