# Generated by Django 5.1.1 on 2024-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_balancehistory_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancehistory',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
