version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"  # Сделаем порт доступным для других сервисов в сети Docker
    environment:
      - DJANGO_SETTINGS_MODULE=service_project.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: service_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
