version: "3.10"

volumes:
  pgdata:
  static:
  media:

services:
  django:
    build:
      context: .
    ports:
      - '8000:8000'
    container_name: service_django
    env_file:
      - .env
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate && 
                    gunicorn --workers=4 --reload --max-requests=1000 service_project.wsgi -b 0.0.0.0:8000"

  nginx:
    container_name: service_nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx/:/etc/nginx/conf.d:ro
    depends_on:
      - service_django


  postgres:
    image: postgres:alpine
    container_name: service_postgres
    restart: always
    environment:
      POSTGRES_DB: service_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data/

