# Generated by Django 5.1.1 on 2024-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoption',
            name='has_period',
            field=models.BooleanField(default=False),
        ),
    ]
