# Generated by Django 5.1.1 on 2024-09-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
