# Generated by Django 5.1.1 on 2024-09-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceoption_has_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название сервиса'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='has_period',
            field=models.BooleanField(default=False, verbose_name='Добавить период'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='service.service', verbose_name='Название сервиса'),
        ),
    ]
