# Generated by Django 5.1.1 on 2024-10-03 09:03

import data_collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyorderanalytics',
            name='info_completed_orders',
            field=models.JSONField(default=data_collector.models.default_info_completed_orders, verbose_name='Выполненые заказы'),
        ),
    ]
