# Generated by Django 5.1.1 on 2024-10-05 10:48

import data_collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0003_alltimeorderanalytics_completed_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltimeorderanalytics',
            options={'verbose_name': 'Полная аналитика', 'verbose_name_plural': 'Общая аналитика'},
        ),
        migrations.AlterField(
            model_name='alltimeorderanalytics',
            name='info_completed_orders',
            field=models.JSONField(default=data_collector.models.default_info_completed_orders, verbose_name='Выполненные заказы за все время'),
        ),
        migrations.AlterField(
            model_name='dailyorderanalytics',
            name='info_completed_orders',
            field=models.JSONField(default=data_collector.models.default_info_completed_orders, verbose_name='Выполненные заказы'),
        ),
    ]
