# Generated by Django 5.1.1 on 2024-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
