# Generated by Django 5.1.1 on 2024-09-19 15:57

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuser',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='total_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='E-mail пользователя'),
        ),
    ]
