# Generated by Django 5.1.1 on 2024-09-27 15:15

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_period_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.CharField(blank=True, choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Hour', max_length=50, null=True, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='replenishmentbalance',
            name='balance_for_replenishment',
            field=djmoney.models.fields.MoneyField(currency_choices=None, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
        migrations.AlterField(
            model_name='replenishmentbalance',
            name='balance_for_replenishment_currency',
            field=djmoney.models.fields.CurrencyField(default='USD', editable=False, max_length=3),
        ),
    ]
