# Generated by Django 5.1.1 on 2024-09-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_period_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replenishmentbalance',
            options={'verbose_name': 'Заказ на пополнение баланса', 'verbose_name_plural': 'Заказы на пополнение баланса'},
        ),
        migrations.AddField(
            model_name='replenishmentbalance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.CharField(blank=True, choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Hour', max_length=50, null=True, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
