# Generated by Django 5.1.1 on 2024-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_period_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.CharField(blank=True, choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Hour', max_length=50, null=True, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
