# Generated by Django 5.1.1 on 2024-10-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_period_alter_order_status_and_more'),
        ('orders', '0009_alter_order_period_alter_order_status_and_more'),
    ]

    operations = [
    ]
