# Generated by Django 5.1.1 on 2024-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20241003_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_completed_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Завершено администратором'),
        ),
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.CharField(blank=True, choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Hour', max_length=50, null=True, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='replenishmentbalance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
