# Generated by Django 5.1.1 on 2024-10-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_period_alter_order_status_and_more'),
        ('orders', '0011_order_admin_completed_order_alter_order_period_and_more'),
    ]

    operations = [
    ]
